name: Code Analyze

on:
  # Triggers the workflow on pull request events to the main branch
  pull_request:
    branches: [ main ]
  push:
    branches: [ "main" ]

jobs:
  code_quality:
    name: Flutter Code Quality
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Runs a set of commands using the runners shell
    - name: Clone repo
      uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: "12.x"

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.7.7"
        channel: 'stable'

    - run: flutter --version

    - name: Get dependencies
      run: flutter pub get

    - name: Code Analyze
      run: flutter analyze

    # Runs a set of commands using the runners shell
    - name: Run tests
      run: flutter analyze